const navBtns=[...document.querySelectorAll('.navbtn[data-view]')],views=[...document.querySelectorAll('.view')];
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));navBtns.forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
navBtns.forEach(b=>b.onclick=()=>showView(b.dataset.view));document.getElementById('scenarioShortcut').onclick=()=>showView('scenario');
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
document.getElementById('syncBtn').onclick=()=>{const b=document.getElementById('syncBtn');b.textContent='Syncing…';setTimeout(()=>{b.textContent='✓ Synced';toast('Data refreshed from pilot feeds');setTimeout(()=>b.textContent='↻ Sync data',1300)},700)};
[...document.querySelectorAll('.rowAction')].forEach(b=>b.onclick=()=>{b.textContent='✓ Done';b.disabled=true;toast('Operational action logged')});
document.getElementById('recalcAll').onclick=()=>{document.getElementById('recalcAll').textContent='Recalculating…';setTimeout(()=>{document.getElementById('netFlow').textContent='742 cs';document.getElementById('recalcAll').textContent='✓ Buffers recalculated';toast('214 hub-SKU buffers refreshed')},700)};
document.getElementById('optimizeMSL').onclick=()=>{document.getElementById('optimizeMSL').textContent='✓ MSL optimized';toast('Cluster-specific MSL recommendations generated')};
const map=document.getElementById('mapArea'),tip=document.getElementById('mapTip');document.querySelectorAll('.pin').forEach(p=>{p.onmouseenter=e=>{tip.style.display='block';tip.innerHTML='<b>'+p.dataset.name+'</b><br>'+p.dataset.info};p.onmousemove=e=>{const r=map.getBoundingClientRect();tip.style.left=(e.clientX-r.left+12)+'px';tip.style.top=(e.clientY-r.top+12)+'px'};p.onmouseleave=()=>tip.style.display='none'});
const priority=document.getElementById('priorityFilter');priority.onchange=()=>document.querySelectorAll('#exceptionTable tbody tr').forEach(r=>r.style.display=(priority.value==='all'||r.dataset.p===priority.value)?'':'none');
document.querySelectorAll('.resolve').forEach(b=>b.onclick=()=>{b.closest('tr').style.opacity='.38';b.textContent='Closed';b.disabled=true;toast('Exception closed and audit trail recorded')});
const beat=document.getElementById('beat'),lead=document.getElementById('lead'),ltVar=document.getElementById('ltVar'),assort=document.getElementById('assort'),comp=document.getElementById('comp'),order=document.getElementById('order');
function calc(){
 const vals={beat:+beat.value,lead:+lead.value,ltv:+ltVar.value,assort:+assort.value,comp:+comp.value,order:+order.value};
 beatVal.textContent=vals.beat;leadVal.textContent=vals.lead;ltVarVal.textContent=vals.ltv.toFixed(1);assortVal.textContent=vals.assort;compVal.textContent=vals.comp;orderVal.textContent=vals.order;
 const fill=Math.max(.90,Math.min(.985,.97-(vals.ltv-2)*.012-(vals.lead-8)*.004));
 let service=vals.assort/100*vals.comp/100*fill*vals.order/100*100; service=Math.min(90,service);
 let cover=18.4+(vals.beat-14)*.53+(vals.lead-6)*1.08+(vals.ltv-1)*1.15; cover=Math.max(18,Math.min(46,cover));
 let cts=1.18+(vals.beat-14)*.008+(vals.lead-8)*.006-(vals.assort-88)*.002; cts=Math.max(1.02,Math.min(1.55,cts));
 serviceOut.textContent=service.toFixed(1)+'%';coverOut.textContent=cover.toFixed(1)+'d';ctsOut.textContent=cts.toFixed(2)+'×';gapOut.textContent=Math.max(0,80-service).toFixed(1)+' pt';
 let risk=(service<70||cover>38)?'High':(service<80||cover>35)?'Medium':'Low';riskOut.textContent=risk;
 let explain='',advice='';
 if(vals.assort<90){explain='Assortment fit is the binding service gate. Adding stock or village-level forecasting will not fix an SKU that is not listed.';advice='Raise cluster-specific MSL coverage first; keep the buffer policy unchanged.'}
 else if(vals.comp<94){explain='Assortment is healthy, but route execution is now constraining service.';advice='Repair fixed-day beat compliance before changing forecast or safety stock.'}
 else if(vals.ltv>2.5||vals.lead>9){explain='Lead-time instability is creating avoidable pipeline and safety stock.';advice='Use cross-dock compression and route reliability; do not inflate the buffer.'}
 else {explain='The operating parameters are inside the intended policy band. The remaining gap should be managed through exceptions and better tertiary signal capture.';advice='Hold policy; improve exception closure, drop size and retailer order capture.'}
 scenarioExplanation.textContent=explain;scenarioAdvice.textContent=advice;document.getElementById('heroService').textContent=service.toFixed(1)+'%';document.getElementById('heroCover').textContent=cover.toFixed(1)+'d';
 return {service,cover,cts,advice};
}
[beat,lead,ltVar,assort,comp,order].forEach(x=>x.oninput=calc);calc();
document.getElementById('resetScenario').onclick=()=>{beat.value=14;lead.value=8;ltVar.value=2;assort.value=88;comp.value=94;order.value=96;calc();toast('Scenario reset')};
let saved=1;document.getElementById('saveScenario').onclick=()=>{const r=calc(),tr=document.createElement('tr');saved++;tr.innerHTML=`<td>Scenario ${saved}</td><td>${r.service.toFixed(1)}%</td><td>${r.cover.toFixed(1)}d</td><td>${r.cts.toFixed(2)}×</td><td>${r.service>=80&&r.cover<=35?'Scale':'Refine'}</td>`;document.querySelector('#savedTable tbody').appendChild(tr);toast('Scenario saved')};
document.querySelectorAll('.switch').forEach(s=>s.onclick=()=>{s.classList.toggle('on');toast(s.classList.contains('on')?'Policy enabled':'Policy disabled')});
const copilot=document.getElementById('copilot');document.getElementById('aiBtn').onclick=()=>{copilot.classList.add('open');document.getElementById('aiBtn').style.display='none'};document.getElementById('closeAI').onclick=()=>{copilot.classList.remove('open');document.getElementById('aiBtn').style.display='block'};
function answerAI(q){q=q.toLowerCase();if(q.includes('service'))return 'Service is below 80% primarily because assortment fit and beat execution multiply with upstream fill and retailer order capture. The next best move is to lift MSL fit before adding inventory.';if(q.includes('inventory')||q.includes('cover'))return 'Inventory cover is most sensitive to beat cycle, lead time and lead-time variability. In this model, cadence and cross-dock compression create more relief than the forecast-accuracy program.';if(q.includes('red')||q.includes('hub'))return 'A red hub means net-flow position has penetrated the red buffer zone. Check whether the driver is an ADU spike or transport variance before expediting.';if(q.includes('forecast'))return 'Use ML at aggregate levels where pooled history and causal signals exist. Below the decoupling point, use dynamic buffers and order-up-to logic rather than village-SKU forecasts.';if(q.includes('fresh'))return 'Freshness is controlled through residual shelf-life gates, velocity routing and assortment gating. Near-expiry stock should move to high-offtake outlets, not follow the normal route sequence.';return 'The operating principle is: forecast the cluster, buffer the village, and manage by exception. Ask me about service, inventory, hubs, forecast or freshness.'}
function sendAI(){const inp=document.getElementById('aiInput'),q=inp.value.trim();if(!q)return;const body=document.getElementById('copilotBody');body.innerHTML+=`<div class="bubble">${q.replace(/</g,'&lt;')}</div><div class="bubble ai">${answerAI(q)}</div>`;inp.value='';body.scrollTop=body.scrollHeight}
document.getElementById('aiSend').onclick=sendAI;document.getElementById('aiInput').onkeydown=e=>{if(e.key==='Enter')sendAI()};
